### ISSUE TITLE
Possibly useful doc

### ISSUE THREAD

**Issue by parkrrrr** [gsuberland/open-network-ms#1]
Adding this as an issue since you don't have a "discussions" tab. 

I came across this documentation that might prove useful if you determine that the card-to-UPS interface really is MODBUS or JBUS:

https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/power-management-software-connectivity/eaton-network-and-modbus-card-ms/eaton-modbus-ms-card-user-guide-34009048xt.pdf.pdf

**Comment by gsuberland** [comment]
Thanks. This is a document I had seen a while ago but couldn't find again. I'll put a copy in the docs section.

I'll take a look at discussions, too. Haven't used them before.

**Comment by gsuberland** [comment]
Document added in 3bf56a2.
